name: example
description: "Example project for the outdoor navigation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  outdoor_navigation:
  # Depend on direct path
    path: ./../
  # Depend on hosted repository
  #  git:
  #    url: https://github.com/Pascalpex/Outdoor-Navigation.git
  #    ref: v1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
