name: outdoor_navigation
description: Provides outdoor positions
version: 1.0.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^8.0.0
  plugin_platform_interface: ^2.1.8
  latlong2: ^0.9.1
  ffi: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        package: de.hhn.outdoor_navigation
        pluginClass: GnssPlugin
      ios:
        pluginClass: GnssPlugin