name: outdoor_navigation
description: Provides outdoor positions
version: 1.0.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^8.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
